token: 138838673:AAHP-XONgU3wl68upNw--fArfnLod-72lTw
main_chat_id: -33208400
allowed_chat_ids: 
  - 50815686 
  - -33208400
blocked_ids:
  - 28215140
sudoers_ids:
  - 50815686
  - 162515395
  - 37975485
  - 78937751
open_door_phrases:
  - open
  - open the door
  - open door
  - door open
  - дверь откройся
  - открыть дверь
  - открыть
  - откройся, мразь
  - откройся мразь
  - открыть
  - откройся
  - открой
  - сим-сим, откройся
  - abrete sesamo
  - -o
  - o
  - отк
  - /open
block_door_phrases:
  - /block
  - /lock
  - заблокировать
unblock_door_phrases:
  - /unblock
  - /unlock
  - разблокировать
get_temp_phrases:
  - /temperature
  - температура
get_hum_phrases:
  - /humidity
  - влажность
door_pin: 10
door_read_pin: 25
lock_pin: 9
dht_pin: 4