token: 138838673:AAHP-XONgU3wl68upNw--fArfnLod-72lTw
main_chat_id: -33208400
allowed_chat_ids: 
  - 50815686 
  - -33208400
sudoers_ids:
  - 50815686
  - 162515395
  - 37975485
  - 78937751
open_door_phrases:
  - open
  - open the door
  - open door
  - door open
  - дверь откройся
  - открыть дверь
  - открыть
  - откройся, мразь
  - откройся мразь
  - открыть
  - откройся
  - открой
  - сим-сим, откройся
  - abrete sesamo
  - -o
  - o
  - отк
  - /open
block_door_phrases:
  - /block
  - заблокировать
unblock_door_phrases:
  - /unblock
  - разблокировать